behaviors:
  JumperAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 4096
      learning_rate: 0.0005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
    max_steps: 100000
    time_horizon: 64
    summary_freq: 10000
    threaded: true
    network_settings:
      hidden_units: 128
      num_layers: 2

